#version: 2.1
#orbs:
    #hello: circleci/hello-build@0.0.5
#workflows:
    #"Hello":
        #jobs:
          #- hello/hello-build

#version: '2.1'
#orbs:
  #node: 'circleci/node:4.1'
  #slack: circleci/slack@4.1
#jobs:
  #deploy:
    #steps:
      #- checkout
      #- node/install-packages
      #- run:
          #command: npm run deploy
      #- slack/notify:
          #channel: qa_internal_bd
          #event: pass
          #template: success_tagged_deploy_1
#workflows:
  #deploy_and_notify:
    #jobs:
      #- deploy:
          #context:
            #- slack-secrets

version: 2.1

orbs:
  maven: circleci/maven@1.1.0
  browser-tools: circleci/browser-tools@1.2.5
  win: circleci/windows@2.3.0

jobs:

  Run_The_build:
     docker: 
      - image: 'cimg/node:17.1.0'
     steps:
      - checkout 
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver 
      - run:
         name: intstall mvn 
         command: |
          sudo apt update -y
          sudo apt install maven -y
  
  
      - run:
          name: check intstall  
          command: |
           google-chrome --version
           chromedriver --version
           mvn --version
           java --version
    
      - run:
          name: check environment  
          command: |
            ls
            echo $(browser)
            echo $(runIdTest)
    
      - run:
          name: check environment  
          command: |
            mvn clean test -D=testng.xml
        
      - run:
          name: Test Done  
          command: | 
           pwd
           ls
  build1:
    executor: win/default
    steps:
      - checkout
      - run: echo 'Hello,From Windows for build1!'
  
  build2:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: The First Step
          command: |
            echo 'Hello,From windows For build3!'
            echo 'This is the delivery pipeline'
      - run:
          name: The third Step
          command: |
            ls -al
            echo '^^^The files in your repo^^^'  
  
  build3:
    executor: win/default
    steps:
      - checkout
      - run: echo 'Hello,From Windows for build2!'
      

  
workflows:
  Run_the_Builds:
    jobs:
      - Run_The_build
      - build1
      - build2
      - build3:
         requires:
           - build1
      # - hold:
      #     type: approval
      #     requires:
      #       - build1
      #       - build2
      # - build3:
      #     requires:
      #       - hold
